name: Deploy to Cloud Run (dev)

on:
  push:
    branches:
      - main  # Reemplaza con tu rama de desarrollo

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: visionary-464813  # Ej: plan-empleo-dev
        install_components: 'beta'

    - name: Build and Push Docker image
      run: |
        IMAGE=gcr.io/visionary-464813/visionary
        gcloud builds submit --tag $IMAGE

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy bio-link \
          --image gcr.io/visionary-464813/visionary \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
