name: Deploy BIOLINK API to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # asegurate de tener tests, o comentá esta línea al principio

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: visionary-464813

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/visionary-464813/biolink-repo/biolink-api:latest .
          docker push us-central1-docker.pkg.dev/visionary-464813/biolink-repo/biolink-api:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy biolink-api \
            --image us-central1-docker.pkg.dev/visionary-464813/biolink-repo/biolink-api:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --quiet
